# Generated by Django 3.0.11 on 2021-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('class_time', models.CharField(choices=[('M', 'Mañana'), ('A', 'Tarde'), ('E', 'Noche')], default='E', max_length=1, verbose_name='Horario')),
                ('free_comment', models.TextField(blank=True, default='', verbose_name='Comentario libre')),
                ('courses', models.ManyToManyField(to='marketing.LiveCourse', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
