# Generated by Django 3.0.11 on 2021-07-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
